### ISSUE TITLE
M0 RFM96 C API leren.

### ISSUE THREAD

**Issue by TomHaels** [DIGIMAD-4/main#2]
* https://cdn-learn.adafruit.com/downloads/pdf/adafruit-feather-m0-radio-with-lora-radio-module.pdf
* https://learn.adafruit.com/adafruit-feather-m0-radio-with-lora-radio-module/using-the-rfm-9x-radio
* https://www.airspayce.com/mikem/arduino/RadioHead/classRH__RF95.html

**Comment by Villadelfia** [comment]
Zeer eenvoudige C api beschikbaar, RadioHead.
