### ISSUE TITLE
Variant master PCB + behuizing met gekozen componenten.

### ISSUE THREAD

**Issue by Villadelfia** [DIGIMAD-4/main#6]

**Comment by Villadelfia** [comment]
Blocker: Fysieke hardware in handen nodig voor accurate dimensies.

Nota: PCB kan lokaal gefabriceerd worden, zal zeer eenvoudig + single layer zijn dus protoboard voldoet.

**Comment by Villadelfia** [comment]
https://github.com/DIGIMAD-4/main/commit/eda2b0980a8407faac626af7cc28709025cd278c

**Comment by 20007082** [comment]
Graag bij de STL ook een printscreen van de render toevoegen.
